// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Station.Infrastructure.Persistence;

#nullable disable

namespace Station.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StationDbContext))]
    [Migration("20260909122944_AddRoomTokenLifetime")]
    partial class AddRoomTokenLifetime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Station.Domain.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pinyin")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("SimplifiedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraditionalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Station.Domain.Models.Favorite", b =>
                {
                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuestId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Station.Domain.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomSessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("MediaSourceId", "RelativePath")
                        .IsUnique();

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastScanAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaSources");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId", "StreamId", "Type")
                        .IsUnique();

                    b.ToTable("MediaTracks");
                });

            modelBuilder.Entity("Station.Domain.Models.PlayHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QueueItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayHistory");
                });

            modelBuilder.Entity("Station.Domain.Models.PlaybackError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRetryable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlaybackErrors");
                });

            modelBuilder.Entity("Station.Domain.Models.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedByGuestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByGuestId");

                    b.HasIndex("SongId");

                    b.HasIndex("RoomSessionId", "Position")
                        .IsUnique();

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("Station.Domain.Models.RoomSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQueuedSongsPerGuest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OpenSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("OpenSlot")
                        .IsUnique();

                    b.ToTable("RoomSessions");
                });

            modelBuilder.Entity("Station.Domain.Models.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscoveredFiles")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("Station.Domain.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompactTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimplifiedTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleInitials")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePinyin")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraditionalTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTitle");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Station.Domain.Models.SongArtist", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId", "Order")
                        .IsUnique();

                    b.ToTable("SongArtists");
                });

            modelBuilder.Entity("Station.Domain.Models.TrackMapping", b =>
                {
                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackingTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultSubtitleTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VocalTrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFileId");

                    b.ToTable("TrackMappings");
                });

            modelBuilder.Entity("Station.Domain.Models.Favorite", b =>
                {
                    b.HasOne("Station.Domain.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Station.Domain.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Station.Domain.Models.Guest", b =>
                {
                    b.HasOne("Station.Domain.Models.RoomSession", "RoomSession")
                        .WithMany("Guests")
                        .HasForeignKey("RoomSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomSession");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaFile", b =>
                {
                    b.HasOne("Station.Domain.Models.MediaSource", "MediaSource")
                        .WithMany("Files")
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Station.Domain.Models.Song", "Song")
                        .WithMany("MediaFiles")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaSource");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaTrack", b =>
                {
                    b.HasOne("Station.Domain.Models.MediaFile", "MediaFile")
                        .WithMany("Tracks")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Station.Domain.Models.QueueItem", b =>
                {
                    b.HasOne("Station.Domain.Models.Guest", "RequestedByGuest")
                        .WithMany()
                        .HasForeignKey("RequestedByGuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Station.Domain.Models.RoomSession", "RoomSession")
                        .WithMany("Queue")
                        .HasForeignKey("RoomSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Station.Domain.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByGuest");

                    b.Navigation("RoomSession");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Station.Domain.Models.SongArtist", b =>
                {
                    b.HasOne("Station.Domain.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Station.Domain.Models.Song", "Song")
                        .WithMany("Artists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Station.Domain.Models.TrackMapping", b =>
                {
                    b.HasOne("Station.Domain.Models.MediaFile", "MediaFile")
                        .WithOne("TrackMapping")
                        .HasForeignKey("Station.Domain.Models.TrackMapping", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Station.Domain.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaFile", b =>
                {
                    b.Navigation("TrackMapping");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Station.Domain.Models.MediaSource", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Station.Domain.Models.RoomSession", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Station.Domain.Models.Song", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("MediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
