import { Heart, Home, ListMusic, Music2, Search, UserRound } from 'lucide-react'
import { Navigate, NavLink, Route, Routes } from 'react-router-dom'

const suggestions = [['告白气球','周杰伦','国语 · 03:35'],['突然好想你','五月天','国语 · 04:26'],['泡沫','邓紫棋','国语 · 04:18'],['喜欢你','Beyond','粤语 · 04:36']]

function DiscoverPage() {
  return <><label className="search-box"><Search aria-hidden="true" /><span className="sr-only">搜索歌曲</span><input placeholder="搜索歌名、歌手或拼音" /></label><section className="now-playing" aria-label="正在播放"><span className="album"><Music2 aria-hidden="true" /></span><div><small>正在播放</small><strong>夜曲 · 周杰伦</strong></div><span>伴奏</span></section><div className="section-tabs"><button className="active">推荐</button><button>热门</button><button>最近新增</button></div><section className="song-list" aria-label="推荐歌曲">{suggestions.map(([title,artist,meta]) => <article className="song-row" key={title}><div><strong>{title}</strong><small>{artist} · {meta}</small></div><button aria-label={`点播 ${title}`}>＋</button></article>)}</section></>
}
function Placeholder({ title }: { title: string }) { return <section className="empty-state"><Music2 aria-hidden="true" /><h2>{title}</h2><p>功能将在当前开发阶段接入真实房间数据。</p></section> }
function RoomShell() { return <main className="phone-shell"><header className="room-header"><div><h1>客厅 KTV</h1><p>房间 KTV-826 · 4 人在线</p></div><span className="connected">已连接</span></header><div className="page-content"><Routes><Route path="discover" element={<DiscoverPage />} /><Route path="queue" element={<Placeholder title="我的点歌" />} /><Route path="favorites" element={<Placeholder title="我的收藏" />} /><Route path="*" element={<Navigate to="discover" replace />} /></Routes></div><nav className="bottom-nav" aria-label="主导航"><NavLink to="/room/discover"><Home aria-hidden="true" />点歌</NavLink><NavLink to="/room/queue"><ListMusic aria-hidden="true" />已点</NavLink><NavLink to="/room/favorites"><Heart aria-hidden="true" />收藏</NavLink><NavLink to="/join"><UserRound aria-hidden="true" />我的</NavLink></nav></main> }
function JoinPage() { return <main className="join-shell"><div className="brand"><span><Music2 aria-hidden="true" /></span><h1>AI-KTV Station</h1><p>加入朋友的家庭 KTV 房间</p></div><form><label>房间码<input inputMode="text" maxLength={6} placeholder="例如 KTV826" /></label><label>昵称<input maxLength={40} placeholder="大家怎么称呼你？" /></label><button type="button">加入房间</button></form></main> }
export function App() { return <Routes><Route path="/join" element={<JoinPage />} /><Route path="/room/*" element={<RoomShell />} /><Route path="*" element={<Navigate to="/join" replace />} /></Routes> }
