import { Heart, Home, ListMusic, Music2, UserRound } from 'lucide-react'
import { type FormEvent, useState } from 'react'
import { Navigate, NavLink, Route, Routes, useNavigate, useSearchParams } from 'react-router-dom'
import { ApiError } from './api/client'
import { DiscoverPage } from './features/catalog/DiscoverPage'
import { QueuePage } from './features/queue/QueuePage'
import { useSession, type RoomRole } from './state/session'
function Placeholder({ title }: { title: string }) { return <section className="empty-state"><Music2 aria-hidden="true" /><h2>{title}</h2><p>功能将在当前开发阶段接入真实房间数据。</p></section> }
function RoomShell() { const { session, setSession } = useSession(); if (!session) return <Navigate to="/join" replace />; return <main className="phone-shell"><header className="room-header"><div><h1>{session.roomName}</h1><p>{session.nickname} · {session.role === 'Host' ? '主持人' : '访客'}</p></div><button className="connection-button" onClick={() => setSession(null)}>退出</button></header><div className="page-content"><Routes><Route path="discover" element={<DiscoverPage />} /><Route path="queue" element={<QueuePage />} /><Route path="favorites" element={<Placeholder title="我的收藏" />} /><Route path="*" element={<Navigate to="discover" replace />} /></Routes></div><nav className="bottom-nav" aria-label="主导航"><NavLink to="/room/discover"><Home aria-hidden="true" />点歌</NavLink><NavLink to="/room/queue"><ListMusic aria-hidden="true" />已点</NavLink><NavLink to="/room/favorites"><Heart aria-hidden="true" />收藏</NavLink><NavLink to="/join"><UserRound aria-hidden="true" />我的</NavLink></nav></main> }
interface JoinResponse { token: string; roomId: string; guestId: string; nickname: string; role: RoomRole; expiresAt: string }
function JoinPage() { const { api, session, setSession } = useSession(); const navigate = useNavigate(); const [params] = useSearchParams(); const [code, setCode] = useState(params.get('code')?.toUpperCase() ?? ''); const [nickname, setNickname] = useState(''); const [error, setError] = useState(''); const [joining, setJoining] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setJoining(true); setError(''); try { const joined = await api.post<JoinResponse>('/api/rooms/join', { joinCode: code, nickname }); setSession({ ...joined, roomName: '客厅 KTV' }); navigate('/room/discover', { replace: true }) } catch (value) { setError(value instanceof ApiError ? value.message : '无法连接到 KTV 主机，请稍后重试。') } finally { setJoining(false) } } return <main className="join-shell"><div className="brand"><span><Music2 aria-hidden="true" /></span><h1>AI-KTV Station</h1><p>加入朋友的家庭 KTV 房间</p></div>{session && <button className="resume-button" onClick={() => navigate('/room/discover')}>继续 {session.roomName}</button>}<form onSubmit={submit}><label>房间码<input value={code} onChange={event => setCode(event.target.value.toUpperCase())} inputMode="text" maxLength={6} placeholder="例如 KTV826" autoComplete="off" required /></label><label>昵称<input value={nickname} onChange={event => setNickname(event.target.value)} maxLength={40} placeholder="大家怎么称呼你？" autoComplete="nickname" required /></label>{error && <p className="form-error" role="alert">{error}</p>}<button type="submit" disabled={joining}>{joining ? '正在加入…' : '加入房间'}</button></form></main> }
export function App() { return <Routes><Route path="/join" element={<JoinPage />} /><Route path="/room/*" element={<RoomShell />} /><Route path="*" element={<Navigate to="/join" replace />} /></Routes> }
